### ISSUE TITLE
When did you code

### ISSUE THREAD

**Issue by ahmad-reza619** [awanisius/ama#2]
Most kids does'nt realize their passion early, but looks like your skills have overgrown more than most of adults of this wkwk land :v so when did you realize to code.

**Comment by awanisius** [comment]
It’s advisable to start to learn code as early as possible!

I started out coding when I was 12 pounding out some ridiculous batch games, then graduated to IRC scripting, then C++, Visual Basic, JavaScript, etc, and this is all within a few years time. It has helped me out immeasurably because in every job I’ve ever been in (since I was 15) I was able to say “Hey, I can make this system better!” and “I can do this in an eightieth the time by using a small C++ program or a macro or whatever!”

PS: Learning to code is simply about learning to translate the principle of cause and effect into repeatable, scalable patterns, known as "programming languages." Everyone knows how to do this at any age, it's just a matter when someone more experienced takes the time to teach programming by experience, **not** by reading a book.

But, books are helpful too
